# Generated by Django 4.2.3 on 2023-07-03 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_app.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users_app", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="баланс"
            ),
        ),
        migrations.AlterField(
            model_name="avataruser",
            name="src",
            field=models.ImageField(
                blank=True,
                default="users_app/avatars/default.png",
                null=True,
                upload_to=users_app.models.profile_avatar_directory_path,
                verbose_name="синий внеземлянин",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
