# Generated by Django 4.2.3 on 2023-07-22 15:33

from django.db import migrations, models
import django.db.models.deletion
import users_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0004_alter_profile_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avataruser",
            name="alt",
            field=models.CharField(
                blank=True, max_length=500, verbose_name="someone else"
            ),
        ),
        migrations.AlterField(
            model_name="avataruser",
            name="src",
            field=models.ImageField(
                blank=True,
                default="users_app/avatars/cat.jpg",
                null=True,
                upload_to=users_app.models.profile_avatar_directory_path,
                verbose_name="someone",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.avataruser",
                verbose_name="someone",
            ),
        ),
    ]
