# Generated by Django 4.2.3 on 2023-07-23 10:19

import django.core.validators
from django.db import migrations, models
import users_app.models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0005_alter_avataruser_alt_alter_avataruser_src_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avataruser",
            name="src",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users_app.models.profile_avatar_directory_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=("png", "jpg", "webp", "jpeg")
                    )
                ],
                verbose_name="someone",
            ),
        ),
    ]
