# Generated by Django 4.2.3 on 2023-07-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0003_profile_balance_alter_avataruser_src_and_more"),
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="заказы",
                to="users_app.profile",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.JSONField(verbose_name="продукты"),
        ),
    ]
