# Generated by Django 4.2.3 on 2023-07-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders_app", "0002_order_user_alter_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.JSONField(blank=True, verbose_name="продукты"),
        ),
    ]
