# Generated by Django 4.2.2 on 2023-07-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0002_product_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.IntegerField(blank=True, default=None, verbose_name="скидка"),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                max_digits=12,
                verbose_name="цена со скидкой",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="limited",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="осталось мало"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="popular",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="популярный продукт"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="freeDelivery",
            field=models.BooleanField(
                blank=True, default=False, verbose_name="бесплатная доставка?"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="название"
            ),
        ),
    ]
