# Generated by Django 4.2.3 on 2023-07-04 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0003_product_discount_product_discount_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecificationOfProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=128, verbose_name="size"),
                ),
                (
                    "value",
                    models.CharField(blank=True, max_length=128, verbose_name="value"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="fullDescription",
            field=models.TextField(
                blank=True, max_length=2000, verbose_name="описание"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="specifications",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="products_app.specificationofproduct",
                verbose_name="спецификация",
            ),
        ),
    ]
