# Generated by Django 4.2.3 on 2023-07-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "products_app",
            "0004_specificationofproduct_product_fulldescription_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currentPage",
                    models.IntegerField(
                        blank=True, default=1, verbose_name="текущая страницы"
                    ),
                ),
                (
                    "lastPage",
                    models.IntegerField(blank=True, verbose_name="последняя страница"),
                ),
                (
                    "items",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="products_app.product",
                        verbose_name="элементы каталога",
                    ),
                ),
            ],
        ),
    ]
