# Generated by Django 4.2.3 on 2023-07-06 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0005_catalog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catalog",
        ),
    ]
