# Generated by Django 4.2.3 on 2023-07-06 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0007_alter_product_count_alter_product_images_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="specifications",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="products_app.specificationofproduct",
                verbose_name="спецификация",
            ),
        ),
    ]
