# Generated by Django 4.2.3 on 2023-07-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products_app", "0008_alter_product_specifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="products_app.category",
            ),
        ),
    ]
